server:
  port: 8088

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/world
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:  
      database: MYSQL  
      show-sql: true  
      properties:  
         dialect: org.hibernate.dialect.MySQL5Dialect  
    data:
        web:
            pageable:
                default-page-size: 3
                page-parameter: pageNumber
                size-parameter: pageSize
            sort:
                sort-parameter: orderBy
